export type TouchBarRoute =
  | 'dashboard'
  | 'members'
  | 'members/new'
  | 'members/detail'
  | 'products'
  | 'products/new'
  | 'products/detail'
  | 'categories'
  | 'sales'
  | 'sales/new'
  | 'points'
  | 'stock'
  | 'cash-register'
  | 'expenses'
  | 'cloud-backup'
  | 'users'
  | 'settings'

export type TouchBarAction =
  | 'navigate:dashboard'
  | 'navigate:members'
  | 'navigate:members/new'
  | 'navigate:products'
  | 'navigate:products/new'
  | 'navigate:categories'
  | 'navigate:categories/new'
  | 'navigate:sales'
  | 'navigate:sales/new'
  | 'navigate:points'
  | 'navigate:stock'
  | 'navigate:cash-register'
  | 'navigate:expenses'
  | 'navigate:cloud-backup'
  | 'navigate:users'
  | 'navigate:settings'
  | 'action:search'
  | 'action:load-points'
  | 'action:stock-entry'
  | 'action:stock-adjustment'
  | 'action:open-cash'
  | 'action:close-cash'
  | 'action:backup-now'
  | 'action:lock'

export interface TouchBarContext {
  route: TouchBarRoute
  cashRegisterOpen?: boolean
}
